spring.application.name=engine
server.port=${SERVER_PORT:8080}

# Desliga o Flyway
spring.flyway.enabled=false

# Mostra as queries no console para facilitar o debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Diz que o padrão ao apertar Play na IDE é rodar o Dev (Postgres)
spring.profiles.active=dev