# Configuração do Banco de Dados (H2 Offline Embutido)
spring.datasource.url=jdbc:h2:file:~/.srm-tau/srm_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cria/Atualiza as tabelas no banco de dados local do cliente
spring.jpa.hibernate.ddl-auto=update